version: '3'

services:
  building-classroom-api:
#    image: building-classroom-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: